### ISSUE TITLE
extend the `jokerfile` to support running other commands, once everything is set up

### ISSUE THREAD

**Issue by toudi** [toudi/joker#10]
the idea would be that you can first launch the stack and then provide entrypoints for launching other commands, something like `go test` or something else which you would later run.

hypothetical syntax:

```yaml
services:
  my-service:
    actions:
      run-tests: go test -v 
```

execution:

```shell
joker action my-service run-tests
```
