### ISSUE TITLE
a service plugin / template system (for a lack of a better word)

### ISSUE THREAD

**Issue by toudi** [toudi/joker#7]
don't know how to call it better. Essentially, I don't like the fact that the jokerfile is so verbose (when you look at the provided postgres sample). what I'd like to achieve would be a simpler user input, like so:

```
services:
   postgres:
      template: postgresql
      params:
          port: 5555
          dbname: some-db-name
          rolename: some-role-name
```

when in use, the `template` would hook into the `up` and `clear` signals and could perform various operations (like removing the data directory or setting up roles and so on)
