### ISSUE TITLE
allow to specify the signal used to shutdown the process

### ISSUE THREAD

**Issue by toudi** [toudi/joker#9]
something like:

```yaml
services:
  my-service:
    shutdown-signal: SIGQUIT
```

whereas the default would be SIGTERM
